export const products = [
  {
    id: 'stone-remover',
    name: 'Stone Remover Kit',
    tagline: 'Kidney & gallbladder stone support',
    concern: 'kidney',
    price: 1499,
    mrp: 2199,
    rating: 4.6,
    image: '/images/stone-remover-kit.png',
  },
  {
    id: 'skin-radiance',
    name: 'Skin Radiance Kit',
    tagline: 'Acne control & glow',
    concern: 'skin',
    price: 1299,
    mrp: 1699,
    rating: 4.5,
    image: '/images/skin-radiance-kit.png',
  },
  {
    id: 'hair-regrowth',
    name: 'Hair Regrowth Kit',
    tagline: 'Hair fall & thinning support',
    concern: 'hair',
    price: 1399,
    mrp: 1899,
    rating: 4.4,
    image: '/images/hair-regrowth-kit.png',
  },
  {
    id: 'dental-care',
    name: 'Dental Care Kit',
    tagline: 'Gum health & fresh breath',
    concern: 'dental',
    price: 899,
    mrp: 1099,
    rating: 4.5,
    image: '/images/dental-care-kit.png',
  },
  {
    id: 'joint-relief',
    name: 'Joint & Pain Relief Kit',
    tagline: 'Mobility & everyday comfort',
    concern: 'joint',
    price: 1199,
    mrp: 1499,
    rating: 4.3,
    image: '/images/joint-pain-relief-kit.png',
  },
  {
    id: 'immunity-booster',
    name: 'Immunity Booster Kit',
    tagline: 'Daily strength & defense',
    concern: 'energy',
    price: 999,
    mrp: 1299,
    rating: 4.6,
    image: '/images/immunity-booster-kit.png',
  },
]

export function getProductById(id) {
  return products.find((p) => p.id === id)
}
