import Link from "next/link";
import { ArrowDownRight, ArrowRight, BadgeCheck, HeartPulse, Leaf, ShieldCheck, Sparkles, Star, Truck } from "lucide-react";
import { CatalogBrowser } from "@/components/catalog-browser";
import { SiteFooter, SiteHeader } from "@/components/site-shell";
import { products } from "@/lib/catalog";

export default function HomePage() {
  return <main className="overflow-hidden bg-[#fffdfa] text-[#27362c]"><SiteHeader />
    <section className="relative mx-auto max-w-[1520px] px-4 pt-4 sm:px-6 lg:px-8">
      <div className="hero-glow relative overflow-hidden rounded-[30px] bg-[#dce9dc] px-6 py-12 sm:rounded-[38px] sm:px-10 sm:py-16 lg:min-h-[615px] lg:px-[8%] lg:py-20">
        <div className="relative z-10 max-w-[590px]">
          <div className="inline-flex items-center gap-2 rounded-full border border-[#ffffffa8] bg-white/55 px-3 py-2 text-[10px] font-bold uppercase tracking-[.15em] text-[#426752] backdrop-blur"><Sparkles size={13} className="text-[#c65e43]" /> Everyday care, elevated</div>
          <h1 className="mt-7 max-w-[580px] font-serif text-[clamp(3.5rem,7vw,6.7rem)] leading-[.86] tracking-[-.055em] text-[#284733]">A little more <em className="font-normal text-[#c5593e]">well.</em><br />Every day.</h1>
          <p className="mt-7 max-w-md text-[15px] leading-7 text-[#58705e] sm:text-base">Medical essentials, wellness rituals, and personal care chosen with real life in mind. Delivered to your door with ease.</p>
          <div className="mt-9 flex flex-wrap items-center gap-3"><Link href="#shop" className="group inline-flex items-center gap-3 rounded-full bg-[#2d624a] px-6 py-4 text-[10px] font-bold uppercase tracking-[.16em] text-white shadow-[0_14px_30px_rgba(42,91,65,.2)] transition hover:-translate-y-0.5 hover:bg-[#234e3b]">Shop essentials <ArrowRight size={15} className="transition group-hover:translate-x-1" /></Link><Link href="#our-story" className="rounded-full px-4 py-4 text-[10px] font-bold uppercase tracking-[.16em] text-[#41644f] transition hover:text-[#bd523a]">Why AIIMS</Link></div>
          <div className="mt-12 flex items-center gap-5 sm:mt-16"><div className="flex -space-x-2">{["#e7b895", "#9abda4", "#d0a6a5", "#8da7c7"].map((color, index) => <span key={color} className="grid h-8 w-8 place-items-center rounded-full border-2 border-[#dce9dc] text-[9px] font-bold text-white" style={{ backgroundColor: color }}>{["M", "A", "J", "S"][index]}</span>)}</div><div><div className="flex gap-0.5 text-[#db8e5e]">{Array.from({ length: 5 }).map((_, index) => <Star key={index} size={13} fill="currentColor" />)}</div><p className="mt-1 text-[10px] font-medium text-[#5e7867]">Loved by 12,000+ everyday people</p></div></div>
        </div>
        <div className="pointer-events-none relative z-[1] mt-10 h-[330px] sm:h-[430px] lg:absolute lg:bottom-0 lg:right-[3%] lg:mt-0 lg:h-[590px] lg:w-[49%]">
          <div className="absolute bottom-[3%] right-[2%] h-[78%] w-[53%] overflow-hidden rounded-t-[100px] rounded-bl-[36px] bg-[#f3bb8c] shadow-[0_26px_38px_rgba(42,76,54,.18)]"><img src="https://images.pexels.com/photos/30270934/pexels-photo-30270934.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=1100&w=900" alt="Healthcare professional with care products" className="h-full w-full object-cover object-[60%_center] mix-blend-multiply" /></div>
          <div className="absolute bottom-[5%] left-[1%] w-[46%] rotate-[-8deg] overflow-hidden rounded-[30px] border-[7px] border-[#f6f1e8] bg-[#eed18d] shadow-[0_18px_35px_rgba(42,76,54,.2)]"><img src="https://images.pexels.com/photos/31251024/pexels-photo-31251024.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=800&w=800" alt="Wellness bottles" className="aspect-square w-full object-cover" /></div>
          <div className="absolute right-[2%] top-[10%] grid h-24 w-24 place-items-center rounded-full border border-white/70 bg-[#ffe5ba] text-center text-[10px] font-bold uppercase leading-4 tracking-[.1em] text-[#b45338] shadow-lg sm:h-28 sm:w-28"><span>Care that<br />feels good</span></div>
          <div className="absolute left-[44%] top-[11%] h-8 w-8 rounded-full bg-[#f5c46d] opacity-80" />
        </div>
      </div>
    </section>
    <section className="border-b border-[#e1e8df] bg-[#f2f6f0] px-5 py-5 sm:px-8"><div className="mx-auto grid max-w-[1360px] grid-cols-1 gap-5 sm:grid-cols-3 sm:gap-8"><TrustItem icon={<Truck size={18} />} title="Free delivery from $45" body="Carefully packed and trackable" /><TrustItem icon={<ShieldCheck size={18} />} title="Quality-assured picks" body="Sourced with standards in mind" /><TrustItem icon={<HeartPulse size={18} />} title="Here when you need us" body="Friendly support, seven days" /></div></section>
    <section id="shop" className="mx-auto max-w-[1360px] px-5 py-20 sm:px-8 lg:py-28"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow">The edit</p><h2 className="mt-3 max-w-lg font-serif text-[clamp(2.65rem,5vw,4.6rem)] leading-[.93] tracking-[-.045em] text-[#2a4232]">Find your feel-good.</h2></div><p className="max-w-xs text-sm leading-6 text-[#6d786e]">Made for your everyday, from the necessary to the nourishing.</p></div><div className="mt-10"><CatalogBrowser products={products} /></div><div className="mt-12 text-center"><Link href="#shop" className="inline-flex items-center gap-2 border-b border-[#7e9583] pb-1 text-[11px] font-bold uppercase tracking-[.15em] text-[#3d674d] transition hover:border-[#c2573d] hover:text-[#c2573d]">Explore the full collection <ArrowDownRight size={15} /></Link></div></section>
    <section className="mx-auto max-w-[1440px] px-4 pb-20 sm:px-6 lg:px-8 lg:pb-28"><div className="grid overflow-hidden rounded-[30px] bg-[#f1dfc6] lg:grid-cols-2"><div className="relative min-h-[390px] overflow-hidden lg:order-2 lg:min-h-[550px]"><img src="https://images.pexels.com/photos/18066458/pexels-photo-18066458.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=1200&w=1100" alt="Natural personal care essentials" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#624c3c]/20 to-transparent" /><div className="absolute bottom-6 left-6 rounded-full bg-[#fffaf2]/90 px-4 py-2 text-[10px] font-bold uppercase tracking-[.14em] text-[#80573c] backdrop-blur">Made for gentle moments</div></div><div className="flex flex-col justify-center px-7 py-14 sm:px-12 lg:px-[14%]"><p className="eyebrow text-[#a75b3e]">Personal care, softened</p><h2 className="mt-4 font-serif text-[clamp(2.7rem,4vw,4.2rem)] leading-[.92] tracking-[-.045em] text-[#544336]">The daily ritual,<br />reconsidered.</h2><p className="mt-6 max-w-md text-[15px] leading-7 text-[#7a6555]">Nourishing formulas and comforting essentials made to sit beautifully in your everyday. A little care can go a long way.</p><Link href="#personal-care" className="mt-8 inline-flex w-fit items-center gap-2 rounded-full border border-[#ba8262] px-5 py-3 text-[10px] font-bold uppercase tracking-[.14em] text-[#8e583e] transition hover:bg-[#b96e4c] hover:text-white">Explore personal care <ArrowRight size={14} /></Link></div></div></section>
    <section id="our-story" className="border-y border-[#dfe7de] bg-[#eaf2e8] px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div className="relative mx-auto w-full max-w-[425px]"><div className="absolute -left-7 -top-6 h-28 w-28 rounded-full bg-[#f2c774] opacity-70 blur-[1px]" /><div className="relative aspect-[.85] overflow-hidden rounded-t-[200px] rounded-b-[38px] bg-[#b2d0b5]"><img src="https://images.pexels.com/photos/30270934/pexels-photo-30270934.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=1100&w=900" alt="Care practitioner holding products" className="h-full w-full object-cover object-center" /></div><div className="absolute -bottom-5 -right-4 rounded-[20px] bg-[#fffdf8] px-5 py-4 shadow-[0_15px_35px_rgba(47,78,55,.16)]"><Leaf className="text-[#4b936c]" size={20} /><p className="mt-2 font-serif text-xl text-[#31523c]">Thoughtful by nature</p></div></div><div><p className="eyebrow">The AIIMS standard</p><h2 className="mt-4 font-serif text-[clamp(2.8rem,5vw,4.7rem)] leading-[.91] tracking-[-.05em] text-[#284432]">Care without<br />the clutter.</h2><p className="mt-6 max-w-lg text-[15px] leading-7 text-[#5e7062]">We believe medical and wellness shopping should feel clear, calm, and human. So we curate the essentials worth making room for — backed by straight-talking information and kind service.</p><div className="mt-8 grid gap-5 sm:grid-cols-2"><div className="rounded-2xl bg-[#f8fbf6] p-5"><BadgeCheck className="text-[#4c9069]" size={22} /><h3 className="mt-3 font-serif text-xl text-[#305039]">Simply trusted</h3><p className="mt-1 text-xs leading-5 text-[#6e7b70]">Clear ingredients and quality-first choices.</p></div><div className="rounded-2xl bg-[#f8fbf6] p-5"><HeartPulse className="text-[#c36750]" size={22} /><h3 className="mt-3 font-serif text-xl text-[#305039]">Warmly helpful</h3><p className="mt-1 text-xs leading-5 text-[#6e7b70]">Real support for everyday questions.</p></div></div></div></div></section>
    <SiteFooter />
  </main>;
}

function TrustItem({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) {
  return <div className="flex items-center justify-center gap-3 text-center sm:justify-start sm:text-left"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-white text-[#3f805d] shadow-sm">{icon}</span><div><p className="text-[11px] font-bold uppercase tracking-[.12em] text-[#355541]">{title}</p><p className="mt-1 text-xs text-[#718073]">{body}</p></div></div>;
}
